button_option: stbc_large
comments: 0
late_load: 0
location: content
node_types:
  news: news
  banners_custom: null
  book: null
  page: null
  page_fz: null
  slider_image: null
option_extras:
  'Google Plus One:plusone': 'Google Plus One:plusone'
  'Facebook Like:fblike': 'Facebook Like:fblike'
option_neworzero: 0
option_onhover: 1
option_shorten: 1
service_option: '''Vkontakte:vkontakte'',''Odnoklassniki:odnoklassniki'',''WhatsApp:whatsapp'',''Facebook:facebook'',''Twitter:twitter'',''Email:email'''
twitter_handle: ''
twitter_recommends: ''
twitter_suffix: ''
webform_options: ''
weight: 10
widget_option: st_multi
cns:
  donotcopy: null
  hashaddress: null
sharethisnodes:
  article:
    full: full
  page:
    full: full
    print: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  banners_custom:
    full: '0'
    print: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  book:
    full: '0'
    print: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  news:
    full: '0'
    print: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  page_fz:
    full: '0'
    print: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  slider_image:
    full: '0'
    print: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
_core:
  default_config_hash: OUePCWmQ_tUOCD4VF7-AP0maPJi2Y18f0JvNTgThhRQ
publisherID: dr-ebca366f-82cf-34be-e5b5-950e47951ecd
langcode: ru
callesi: '0'
